#!/usr/bin/env python3
"""For each `_pad.s` sidecar generated by `trim-trailing-nops.py`, add a
`#pragma GLOBAL_ASM(...)` line in the corresponding `.c` file after the
function's `INCLUDE_ASM` line OR after the closing `}` of its decompiled C
body.

Idempotent: skips functions whose pragma is already present.

Usage:
    python3 scripts/patch-pad-pragmas.py <segment>      # one segment
    python3 scripts/patch-pad-pragmas.py --all          # all segments
    python3 scripts/patch-pad-pragmas.py --dry-run ...  # report only
"""
import os
import re
import sys
from pathlib import Path


def find_segment_c_files(seg: str) -> list[Path]:
    """Return all .c files in src/<seg>/."""
    src_dir = Path(f"src/{seg}")
    if not src_dir.exists():
        return []
    return sorted(src_dir.glob("*.c"))


def find_sidecars(seg: str) -> dict[str, str]:
    """Return {func_name: pragma_path} for each <func>_pad.s sidecar."""
    sidecars = {}
    for asm_root in [Path(f"asm/nonmatchings/{seg}"), Path(f"asm/nonmatchings/{seg}/{seg}")]:
        if not asm_root.exists():
            continue
        for pad_file in asm_root.glob("*_pad.s"):
            func_name = pad_file.stem[:-4]  # strip "_pad"
            # The pragma path is relative to project root
            sidecars[func_name] = str(pad_file)
    return sidecars


def patch_c_file(path: Path, sidecars: dict[str, str], dry_run: bool = False) -> int:
    """Patch <path>: add `#pragma GLOBAL_ASM(...)` after each function with a
    sidecar. Returns number of pragmas added."""
    content = path.read_text()
    new_content = content
    added = 0

    for func_name, pad_path in sidecars.items():
        pragma_line = f'#pragma GLOBAL_ASM("{pad_path}")'

        # Skip if pragma already present
        if pragma_line in new_content:
            continue

        # Pattern A: function is INCLUDE_ASM'd
        include_asm_re = re.compile(
            rf'(INCLUDE_ASM\([^)]*,\s*{re.escape(func_name)}\);)',
            re.MULTILINE
        )
        m = include_asm_re.search(new_content)
        if m:
            insert_at = m.end()
            new_content = new_content[:insert_at] + "\n" + pragma_line + new_content[insert_at:]
            added += 1
            continue

        # Pattern B: function is decompiled. Find `<retty> func_name(args) {`
        # and locate matching close brace.
        decomp_re = re.compile(
            rf'^[\w*\s]+\s+{re.escape(func_name)}\s*\([^)]*\)\s*\{{',
            re.MULTILINE
        )
        m = decomp_re.search(new_content)
        if m:
            # Walk braces from the opening { to find matching }
            i = m.end() - 1  # points at the {
            depth = 0
            while i < len(new_content):
                if new_content[i] == '{':
                    depth += 1
                elif new_content[i] == '}':
                    depth -= 1
                    if depth == 0:
                        break
                i += 1
            if i < len(new_content):
                insert_at = i + 1
                new_content = new_content[:insert_at] + "\n" + pragma_line + new_content[insert_at:]
                added += 1
                continue

        # Pattern C: NON_MATCHING wrap. Find the `#endif` after the `INCLUDE_ASM`
        # and insert pragma after that.
        nm_wrap_re = re.compile(
            rf'(INCLUDE_ASM\([^)]*,\s*{re.escape(func_name)}\);.*?#endif)',
            re.DOTALL
        )
        m = nm_wrap_re.search(new_content)
        if m:
            insert_at = m.end()
            new_content = new_content[:insert_at] + "\n" + pragma_line + new_content[insert_at:]
            added += 1
            continue

        print(f"  WARN: couldn't find {func_name} in {path}", file=sys.stderr)

    if not dry_run and added > 0:
        path.write_text(new_content)

    return added


def patch_segment(seg: str, dry_run: bool = False) -> int:
    sidecars = find_sidecars(seg)
    if not sidecars:
        return 0

    c_files = find_segment_c_files(seg)
    if not c_files:
        print(f"  WARN: no .c files for {seg}", file=sys.stderr)
        return 0

    total = 0
    for c_file in c_files:
        # Each .c file may have a subset of the sidecars
        added = patch_c_file(c_file, sidecars, dry_run)
        if added > 0:
            print(f"  {c_file}: +{added} pragmas")
        total += added
    return total


def main():
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    args = [a for a in args if a != "--dry-run"]

    if not args:
        print(__doc__)
        sys.exit(1)

    if args[0] == "--all":
        segments = sorted(p.name for p in Path("asm/nonmatchings").iterdir() if p.is_dir())
    else:
        segments = args

    grand_total = 0
    for seg in segments:
        added = patch_segment(seg, dry_run)
        if added > 0:
            print(f"{seg}: {added} pragmas added")
            grand_total += added

    if dry_run:
        print(f"\n[DRY RUN] would add {grand_total} pragmas")
    else:
        print(f"\nAdded {grand_total} pragmas total")


if __name__ == "__main__":
    main()
