#!/usr/bin/env python3
"""Trim trailing 0x00000000 padding from each function's `.s` body and emit
a sidecar `<func>_pad.s` containing the pad bytes for re-injection via
GLOBAL_ASM after the C body.

Why: USO `.s` files generated by `generate-uso-asm.py` bundle inter-function
alignment nops into each function's `nonmatching SIZE`. When a function is
INCLUDE_ASM'd, the .o has the right size; when re-decompiled to C, the .o is
short by N*4 bytes and objdiff caps at ~80 % match (per
`feedback_function_trailing_nop_padding.md`).

This script splits the bundled-padding into:
- `<func>.s`     — body only (trimmed `nonmatching SIZE`)
- `<func>_pad.s` — the trailing nops as raw `.fill` (no symbol)

Then `<func>_pad.s` is meant to be referenced from the .c file via
`#pragma GLOBAL_ASM(...)` after the function body — keeping the inter-function
layout identical regardless of whether the function is INCLUDE_ASM or C.

Usage:
    python3 scripts/trim-trailing-nops.py <segment_name>     # trim one segment
    python3 scripts/trim-trailing-nops.py --all              # trim all segments
    python3 scripts/trim-trailing-nops.py --dry-run <seg>    # report only

Idempotent: re-running on already-trimmed files is a no-op.
"""
import os
import re
import sys
from pathlib import Path


def trim_one_function(path: Path, dry_run: bool = False) -> tuple[int, int]:
    """Returns (trail_count, body_count_after_trim). trail_count is bytes
    moved to sidecar."""
    content = path.read_text()
    lines = content.split("\n")

    # Locate body: lines matching `    /* OFFSET ABS BYTES */  .word 0xNNNN`
    body_idx = []  # indices in `lines` that are body instructions
    for i, line in enumerate(lines):
        if "/*" in line and ".word" in line:
            body_idx.append(i)

    if not body_idx:
        return (0, 0)

    # Count trailing 0x00000000 lines from the end of the body
    trail = 0
    for i in reversed(body_idx):
        if "0x00000000" in lines[i]:
            trail += 1
        else:
            break

    # Don't trim functions that are entirely zero (probably data misidentified)
    if trail == len(body_idx):
        return (0, len(body_idx))

    if trail == 0:
        return (0, len(body_idx))

    # Preserve the delay-slot nop after the final `jr ra` (0x03E00008).
    # Pattern: ...non_zero_jr_ra ; nop (delay) ; <padding nops>...
    # The first trailing nop is the delay slot — keep it.
    # Only trim "extra" trailing nops beyond the delay slot.
    last_non_zero_idx = body_idx[-trail - 1] if trail < len(body_idx) else None
    if last_non_zero_idx is not None and "0x03E00008" in lines[last_non_zero_idx]:
        # `jr ra` immediately precedes the trailing nops: first nop is real (delay slot).
        trail -= 1

    if trail == 0:
        return (0, len(body_idx))

    # Trim: remove the last `trail` body lines, also fix `nonmatching SIZE`
    keep_end = body_idx[-trail]  # first line to remove
    new_lines = lines[:keep_end] + lines[body_idx[-1] + 1:]

    # Update the `nonmatching name, 0xSIZE` header
    new_size = (len(body_idx) - trail) * 4
    for i, line in enumerate(new_lines):
        m = re.match(r"^(nonmatching\s+\S+,\s*)0x[0-9A-Fa-f]+(.*)$", line)
        if m:
            new_lines[i] = f"{m.group(1)}0x{new_size:X}{m.group(2)}"
            break

    if dry_run:
        return (trail, len(body_idx) - trail)

    path.write_text("\n".join(new_lines))

    # Emit sidecar pad file
    pad_path = path.with_name(path.stem + "_pad.s")
    pad_name = f"_pad_{path.stem}"
    pad_lines = [
        f"/* trailing alignment padding for {path.stem} */",
        f"glabel {pad_name}, local",
    ]
    for _ in range(trail):
        pad_lines.append(".word 0x00000000")
    pad_lines.append(f"endlabel {pad_name}")
    pad_path.write_text("\n".join(pad_lines) + "\n")

    return (trail, len(body_idx) - trail)


def trim_segment(seg: str, dry_run: bool = False) -> dict:
    """Returns {func_name: trail_word_count}."""
    flat = Path(f"asm/nonmatchings/{seg}")
    nested = Path(f"asm/nonmatchings/{seg}/{seg}")
    # Prefer nested layout if it has .s files (USO style)
    if nested.exists() and any(nested.glob("*.s")):
        asm_dir = nested
    elif flat.exists() and any(flat.glob("*.s")):
        asm_dir = flat
    else:
        print(f"  segment {seg}: no asm dir found", file=sys.stderr)
        return {}

    trimmed = {}
    for s_file in sorted(asm_dir.glob("*.s")):
        # Skip already-emitted sidecars
        if s_file.stem.endswith("_pad"):
            continue
        trail, body = trim_one_function(s_file, dry_run)
        if trail > 0:
            trimmed[s_file.stem] = trail
    return trimmed


def main():
    args = sys.argv[1:]
    dry_run = False
    if "--dry-run" in args:
        dry_run = True
        args.remove("--dry-run")

    if not args:
        print(__doc__)
        sys.exit(1)

    if args[0] == "--all":
        segments = sorted(p.name for p in Path("asm/nonmatchings").iterdir() if p.is_dir())
    else:
        segments = args

    grand_total_funcs = 0
    grand_total_bytes = 0
    for seg in segments:
        trimmed = trim_segment(seg, dry_run)
        if trimmed:
            total_bytes = sum(t * 4 for t in trimmed.values())
            print(f"{seg}: {len(trimmed)} funcs trimmed, {total_bytes} bytes moved to sidecars")
            grand_total_funcs += len(trimmed)
            grand_total_bytes += total_bytes
        else:
            print(f"{seg}: nothing to trim")

    if dry_run:
        print(f"\n[DRY RUN] would trim {grand_total_funcs} functions, {grand_total_bytes} bytes")
    else:
        print(f"\nTrimmed {grand_total_funcs} functions, {grand_total_bytes} bytes total")


if __name__ == "__main__":
    main()
