/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'baserom.z64'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
typedef void *__builtin_va_list;

/* 2 */
typedef void **va_list;

/* 3 */
typedef int BOOL;

